github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/app-monitoring-maintainers"

helpers:
  "bin/helper": "$GOMOD/cmd/helper"

package:
  repositories:   ["docker.io/paketobuildpacks/opentelemetry"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
  - registry: docker.io
    username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
    password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:   opentelemetry-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       opentelemetry-javaagent.jar
    owner:      open-telemetry
    repository: opentelemetry-java-instrumentation
    tag_filter: v(.*)
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
